"""
utils/logger.py

Centralized logging with two distinct output channels:

1. Console logger  (existing, unchanged)
   Structured log lines for the running server process.

2. Correlation audit log  (NEW — append-only JSONL file)
   Every inbound request gets a UUID correlation_id that is:
     • Generated by the middleware in main.py BEFORE the request is processed.
     • Written to logs/audit.jsonl as an immutable, append-only record.
     • Embedded in the prediction log for end-to-end traceability.

   The JSONL format (one JSON object per line) is:
     • Append-only by design — records are never edited or deleted in place.
     • Machine-readable for downstream SIEM / compliance tooling.
     • Each line is a self-contained snapshot; no cross-record dependencies.

   Audit record schema
   -------------------
   {
       "correlation_id": str,          ← UUID-4
       "timestamp_utc":  str,          ← ISO-8601
       "event":          str,          ← "request_received" | "prediction_complete"
       "path":           str,          ← e.g. "/hiring/predict"
       "method":         str,          ← "POST"
       "payload":        dict | null,  ← sanitised request body (sensitive attrs removed)
       "model_metadata": dict,         ← version, variant, loaded_at
       "result":         dict | null,  ← populated on prediction_complete
   }

   Why append-only?
   ----------------
   Immutability gives audit logs evidential weight.  Opening the file in
   "a" (append) mode on every write, combined with OS-level file-locking via
   a threading.Lock, ensures:
     • No record is ever overwritten.
     • Concurrent request handlers do not interleave partial JSON lines.
     • The file can be rotated externally (logrotate / cloud log agent)
       without disrupting the running process — the next write opens a
       fresh descriptor on the rotated file.
"""

from __future__ import annotations

import json
import logging
import os
import threading
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, Optional

# ─── Audit log configuration ─────────────────────────────────────────────────

AUDIT_LOG_DIR  = Path(os.getenv("AUDIT_LOG_DIR", "logs"))
AUDIT_LOG_PATH = AUDIT_LOG_DIR / "audit.jsonl"

# One process-wide lock — guards append writes across all async/thread workers.
_audit_lock = threading.Lock()


def _ensure_log_dir() -> None:
    """Create the log directory if it does not exist yet."""
    AUDIT_LOG_DIR.mkdir(parents=True, exist_ok=True)


# ─── Console logger setup ─────────────────────────────────────────────────────

def setup_logger(name: str, level: int = logging.INFO) -> logging.Logger:
    """
    Create (or retrieve) a named console logger with consistent formatting.

    Usage::

        logger = setup_logger("hiring")
    """
    log_level = getattr(logging, os.getenv("LOG_LEVEL", "INFO").upper(), logging.INFO)
    logger    = logging.getLogger(name)

    if not logger.handlers:
        handler = logging.StreamHandler()
        fmt     = logging.Formatter(
            "[%(asctime)s] %(levelname)s [%(name)s] %(message)s",
            datefmt="%Y-%m-%d %H:%M:%S",
        )
        handler.setFormatter(fmt)
        logger.addHandler(handler)

    logger.setLevel(log_level)
    return logger


# ── Module-level prediction console logger ────────────────────────────────────
_pred_logger = setup_logger("predictions")


# ─── Correlation audit log ────────────────────────────────────────────────────

def log_correlation_event(
    correlation_id: str,
    event:          str,
    path:           str,
    method:         str,
    payload:        Optional[Dict[str, Any]] = None,
    model_metadata: Optional[Dict[str, Any]] = None,
    result:         Optional[Dict[str, Any]] = None,
) -> None:
    """
    Append one structured audit record to logs/audit.jsonl.

    This function is intentionally synchronous and blocking so that the record
    is durably written BEFORE the response is returned to the caller.
    Concurrent writes are serialised by _audit_lock.

    Parameters
    ----------
    correlation_id  : UUID-4 string generated by the middleware.
    event           : "request_received" or "prediction_complete".
    path            : Request URL path (e.g. "/hiring/predict").
    method          : HTTP method ("POST", "GET", …).
    payload         : Sanitised request body — sensitive_value keys are removed
                      before this function is called (see middleware in main.py).
    model_metadata  : Dict from registry.get_metadata() — version, path, loaded_at.
    result          : Prediction result dict (populated on prediction_complete).
    """
    _ensure_log_dir()

    record: Dict[str, Any] = {
        "correlation_id": correlation_id,
        "timestamp_utc":  datetime.now(timezone.utc).isoformat(),
        "event":          event,
        "path":           path,
        "method":         method,
        "payload":        payload,
        "model_metadata": model_metadata,
        "result":         result,
    }

    line = json.dumps(record, default=str)   # default=str handles Path objects etc.

    with _audit_lock:
        with open(AUDIT_LOG_PATH, "a", encoding="utf-8") as fh:
            fh.write(line + "\n")
            fh.flush()                       # flush to OS buffer immediately

    _pred_logger.debug(
        f"[AUDIT] corr={correlation_id[:8]}… event={event} path={path}"
    )


# ─── Prediction console log ───────────────────────────────────────────────────

def log_prediction(
    domain:          str,
    input_data:      dict,
    prediction:      int | float,
    prediction_label: str,
    explanation:     str,
    fairness_result: dict,
    correlation_id:  Optional[str] = None,
) -> None:
    """
    Emit a structured JSON prediction event to the console logger.

    Sensitive attributes are deliberately excluded — they are recorded in
    fairness_result without individual identifiers.
    """
    record = {
        "timestamp":        datetime.now(timezone.utc).isoformat(),
        "correlation_id":   correlation_id,
        "domain":           domain,
        "input":            input_data,
        "prediction":       prediction,
        "prediction_label": prediction_label,
        "explanation":      explanation,
        "fairness": {
            "sensitive_attribute": fairness_result.get("sensitive_attribute"),
            "is_fair":             fairness_result.get("is_fair"),
            "warning":             fairness_result.get("warning"),
        },
    }
    _pred_logger.info(json.dumps(record))
