"""
utils/logger.py  —  Phase 4: PII masking on every log write path

Two output channels
-------------------
1.  Console logger  — structured JSON lines, all PII automatically masked
    before emission via PIIMasker.mask().

2.  Correlation audit log (logs/audit.jsonl) — append-only JSONL file,
    all PII masked before the record is serialised and written.

PII masking contract
---------------------
Every string that enters a log record passes through pii_masker.mask()
before it is serialised.  This covers:

  • Request payloads written by log_correlation_event()
  • Prediction input_data written by log_prediction()
  • Free-text explanation strings (regex-scrubbed)
  • Any nested dict / list in result or model_metadata

The masking is applied at the logger boundary — callers do not need to
pre-sanitise values.  Sensitive attribute *names* (gender, ethnicity, …)
are whitelisted so the fairness field "sensitive_attribute: gender" remains
readable; only *values* (the actual demographic data) are pseudonymised.

Audit log immutability
-----------------------
Identical to Phase 1–3: append-only "a" mode + threading.Lock ensures no
record is ever overwritten and concurrent handlers never interleave.

Environment variables
---------------------
AUDIT_LOG_DIR      — directory for audit.jsonl  (default: "logs")
LOG_LEVEL          — DEBUG | INFO | WARNING | ERROR  (default: INFO)
PII_MASK_ENABLED   — "false" to disable masking in local dev  (default: "true")
PII_HASH_SALT      — salt for SHA-256 pseudonymisation  (default: "quantum")
"""

from __future__ import annotations

import json
import logging
import os
import threading
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, Optional

from utils.pii import pii_masker

# ─── Audit log configuration ─────────────────────────────────────────────────

AUDIT_LOG_DIR  = Path(os.getenv("AUDIT_LOG_DIR", "logs"))
AUDIT_LOG_PATH = AUDIT_LOG_DIR / "audit.jsonl"

# One process-wide write lock — serialises concurrent async/thread appends.
_audit_lock = threading.Lock()


def _ensure_log_dir() -> None:
    AUDIT_LOG_DIR.mkdir(parents=True, exist_ok=True)


# ─── Console logger setup ─────────────────────────────────────────────────────

def setup_logger(name: str, level: int = logging.INFO) -> logging.Logger:
    """
    Create (or retrieve) a named console logger with consistent formatting.

    PII note: callers are responsible for masking values before passing them
    to logger.info() / logger.error() etc.  The prediction-specific helpers
    log_prediction() and log_correlation_event() apply masking automatically.
    """
    log_level = getattr(logging, os.getenv("LOG_LEVEL", "INFO").upper(), logging.INFO)
    lg        = logging.getLogger(name)

    if not lg.handlers:
        handler = logging.StreamHandler()
        fmt     = logging.Formatter(
            "[%(asctime)s] %(levelname)s [%(name)s] %(message)s",
            datefmt="%Y-%m-%d %H:%M:%S",
        )
        handler.setFormatter(fmt)
        lg.addHandler(handler)

    lg.setLevel(log_level)
    return lg


# Module-level prediction console logger
_pred_logger = setup_logger("predictions")


# ─── PII-safe serialisation ───────────────────────────────────────────────────

def _safe_dumps(obj: Any) -> str:
    """
    JSON-serialise *obj* after running PII masking over the full object graph.

    Steps:
    1. pii_masker.mask(obj)  — deep-walk, pseudonymise PII keys, scrub strings.
    2. json.dumps(masked)    — serialise; default=str handles Path / datetime.
    """
    masked = pii_masker.mask(obj)
    return json.dumps(masked, default=str)


# ─── Correlation audit log ────────────────────────────────────────────────────

def log_correlation_event(
    correlation_id: str,
    event:          str,
    path:           str,
    method:         str,
    payload:        Optional[Dict[str, Any]] = None,
    model_metadata: Optional[Dict[str, Any]] = None,
    result:         Optional[Dict[str, Any]] = None,
) -> None:
    """
    Append one PII-masked, immutable audit record to logs/audit.jsonl.

    All four variable-content fields (payload, model_metadata, result, and
    the correlation_id itself) are passed through pii_masker.mask() before
    serialisation.  The record structure is preserved — only PII values are
    replaced with pseudonyms or redaction markers.

    Parameters
    ----------
    correlation_id  : UUID-4 string generated by the middleware.
    event           : "request_received" | "prediction_complete".
    path            : Request URL path, e.g. "/hiring/predict".
    method          : HTTP method ("POST", "GET", …).
    payload         : Sanitised request body (sensitive attr *keys* already
                      removed by middleware; this function additionally masks
                      any PII that slipped through in field *values*).
    model_metadata  : Dict from registry.get_metadata() — version, path, etc.
    result          : Prediction result dict (populated on prediction_complete).
    """
    _ensure_log_dir()

    record: Dict[str, Any] = {
        "correlation_id": correlation_id,          # UUID — not PII
        "timestamp_utc":  datetime.now(timezone.utc).isoformat(),
        "event":          event,
        "path":           path,
        "method":         method,
        "payload":        pii_masker.mask(payload),
        "model_metadata": pii_masker.mask(model_metadata),
        "result":         pii_masker.mask(result),
    }

    line = json.dumps(record, default=str)

    with _audit_lock:
        with open(AUDIT_LOG_PATH, "a", encoding="utf-8") as fh:
            fh.write(line + "\n")
            fh.flush()

    _pred_logger.debug(
        f"[AUDIT] corr={correlation_id[:8]}… event={event} path={path}"
    )


# ─── Prediction console log ───────────────────────────────────────────────────

def log_prediction(
    domain:           str,
    input_data:       dict,
    prediction:       int | float,
    prediction_label: str,
    explanation:      str,
    fairness_result:  dict,
    correlation_id:   Optional[str] = None,
) -> None:
    """
    Emit a PII-masked structured JSON prediction event to the console logger.

    Masking applied
    ---------------
    input_data   — deep-walked; any leaked PII in feature values is pseudonymised.
    explanation  — free-text scrubbed by regex patterns (e.g. names, IPs).
    fairness     — only the attribute *name* and boolean flags are logged;
                   sensitive *values* are never present in fairness_result
                   (stripped at the router layer before this is called).
    """
    safe_input       = pii_masker.mask(input_data)
    safe_explanation = pii_masker.mask_str(explanation)

    record = {
        "timestamp":        datetime.now(timezone.utc).isoformat(),
        "correlation_id":   correlation_id,       # UUID — not PII
        "domain":           domain,
        "input":            safe_input,
        "prediction":       prediction,
        "prediction_label": prediction_label,
        "explanation":      safe_explanation,
        "fairness": {
            # sensitive_attribute is the field *name* (e.g. "gender") — not PII
            "sensitive_attribute": fairness_result.get("sensitive_attribute"),
            "is_fair":             fairness_result.get("is_fair"),
            "warning":             pii_masker.mask_str(
                str(fairness_result.get("warning") or "")
            ) or None,
        },
    }

    _pred_logger.info(_safe_dumps(record))
